mealie:
  base_url: https://mealie.local
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb25nX3Rva2VuIjp0cnVlLCJpZCI6IjQ4ZmY3MjYxLTgxN2EtNDNhOS04OWRlLTYzZWU2OWRkNGEzZSIsIm5hbWUiOiJtZWFsaWUtYWktaW1wb3J0ZXIiLCJpbnRlZ3JhdGlvbl9pZCI6ImdlbmVyaWMiLCJleHAiOjE5MTc4NTI0MTh9.RyCTthoII9MmGHBaJcxAZTyfq3ydSNwDZsyYn1B8wDI
  verify_ssl: false
  ca_bundle: null
processing:
  output_folder: data/pipeline
  language: de
ingredients:
  fuzzy_threshold: 90
  cache_dir: data/cache
  default_category: Sonstiges
  default_category_color: '#959595'
  use_llm_classifier: true
  use_llm_forms: true
llm:
  provider: openai
  api_key: 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
  base_url: https://api.openai.com/v1
  timeout: 240
  model: gpt-5-mini
  vision_model: gpt-5-mini
  temperature: null
  max_tokens: null
  models:
    - id: gpt-5-mini
      supportsSampling: false
    - id: gpt-5-nano
      supportsSampling: false
    - id: gpt-4.1-mini
      supportsSampling: true
    - id: gpt-4.1-nano
      supportsSampling: true
